"""Message types."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from py_coding_agent.domain.message_id import MessageId

if TYPE_CHECKING:
    from py_coding_agent.domain.tool_call import ToolCall
    from py_coding_agent.domain.tool_call_id import ToolCallId


@dataclass(frozen=True)
class UserMessage:
    """A message sent by the user.

    Immutable value object.
    """

    id: MessageId = field(default_factory=MessageId)
    text: str = ""
    role: str = field(init=False, default="user")


@dataclass(frozen=True)
class AssistantMessage:
    """A message generated by the assistant.

    May include tool calls that the agent must execute.
    """

    id: MessageId = field(default_factory=MessageId)
    text: str = ""
    tool_calls: tuple[ToolCall, ...] = ()
    role: str = field(init=False, default="assistant")


@dataclass(frozen=True)
class ToolResultMessage:
    """The result of a tool execution, returned to the assistant.

    Links back to the ToolCall that produced it.
    """

    tool_call_id: ToolCallId
    content: str = ""
    is_error: bool = False
    id: MessageId = field(default_factory=MessageId)
    role: str = field(init=False, default="tool")
